# Generated by Django 2.2 on 2019-05-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20190501_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
