# Generated by Django 2.2 on 2019-05-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20190503_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FileField(blank=True, default='static/error.jpg', null=True, upload_to=''),
        ),
    ]
