# Generated by Django 2.2 on 2019-05-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
