# Generated by Django 2.2 on 2019-08-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
    ]
