# Generated by Django 2.2 on 2019-08-13 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20190813_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pictureb',
            field=models.FileField(blank=True, default='static/error.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewb',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
